require 'faker'

###
puts "Seeding users..."
user1 = User.create!(username: "user1", password: "password1", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user2 = User.create!(username: "user2", password: "password2", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user3 = User.create!(username: "user3", password: "password3", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user4 = User.create!(username: "user4", password: "password4", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user5 = User.create!(username: "user5", password: "password5", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user6 = User.create!(username: "user1", password: "password1", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user7 = User.create!(username: "user2", password: "password2", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user8 = User.create!(username: "user3", password: "password3", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user9 = User.create!(username: "user4", password: "password4", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user10 = User.create!(username: "user5", password: "password5", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user11 = User.create!(username: "user1", password: "password1", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user12 = User.create!(username: "user2", password: "password2", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user13 = User.create!(username: "user3", password: "password3", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user14 = User.create!(username: "user4", password: "password4", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user15 = User.create!(username: "user5", password: "password5", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user16 = User.create!(username: "user1", password: "password1", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user17 = User.create!(username: "user2", password: "password2", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user18 = User.create!(username: "user3", password: "password3", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user19 = User.create!(username: "user4", password: "password4", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user20 = User.create!(username: "user5", password: "password5", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user21 = User.create!(username: "user1", password: "password1", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user22 = User.create!(username: "user2", password: "password2", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user23 = User.create!(username: "user3", password: "password3", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user24 = User.create!(username: "user4", password: "password4", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user25 = User.create!(username: "user5", password: "password5", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user26 = User.create!(username: "user1", password: "password1", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user27 = User.create!(username: "user2", password: "password2", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user28 = User.create!(username: "user3", password: "password3", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user29 = User.create!(username: "user4", password: "password4", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user30 = User.create!(username: "user5", password: "password5", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user31 = User.create!(username: "user1", password: "password1", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user32 = User.create!(username: "user2", password: "password2", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user33 = User.create!(username: "user3", password: "password3", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user34 = User.create!(username: "user4", password: "password4", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user35 = User.create!(username: "user5", password: "password5", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user36 = User.create!(username: "user1", password: "password1", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user37 = User.create!(username: "user2", password: "password2", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user38 = User.create!(username: "user3", password: "password3", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user39 = User.create!(username: "user4", password: "password4", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')
user40 = User.create!(username: "user5", password: "password5", name: Faker::Creature::Dog.name, breed: Faker::Creature::Dog.breed, email: Faker::Internet.email, bio: Faker::Quote.yoda, image_url: 'https://loremflickr.com/320/240/dog')









###
puts "Seeding woofs..."
woof1 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=1', woof_content: Faker::Quote.famous_last_words)
woof2 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=2', woof_content: Faker::Quote.famous_last_words)
woof3 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=3', woof_content: Faker::Quote.famous_last_words)
woof4 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=50', woof_content: Faker::Quote.famous_last_words)
woof5 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=4', woof_content: Faker::Quote.famous_last_words)
woof6 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=5', woof_content: Faker::Quote.famous_last_words)
woof7 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=6', woof_content: Faker::Quote.famous_last_words)
woof8 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=7', woof_content: Faker::Quote.famous_last_words)
woof9 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=8', woof_content: Faker::Quote.famous_last_words)
woof10 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=9', woof_content: Faker::Quote.famous_last_words)
woof11 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=10', woof_content: Faker::Quote.famous_last_words)
woof12 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=11', woof_content: Faker::Quote.famous_last_words)
woof13 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=12', woof_content: Faker::Quote.famous_last_words)
woof14 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=13', woof_content: Faker::Quote.famous_last_words)
woof15 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=14', woof_content: Faker::Quote.famous_last_words)
woof16 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=15', woof_content: Faker::Quote.famous_last_words)
woof17 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=16', woof_content: Faker::Quote.famous_last_words)
woof18 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=17', woof_content: Faker::Quote.famous_last_words)
woof19 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=18', woof_content: Faker::Quote.famous_last_words)
woof20 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=19', woof_content: Faker::Quote.famous_last_words)
woof21 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=20', woof_content: Faker::Quote.famous_last_words)
woof22 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=21', woof_content: Faker::Quote.famous_last_words)
woof23 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=22', woof_content: Faker::Quote.famous_last_words)
woof24 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=23', woof_content: Faker::Quote.famous_last_words)
woof25 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=24', woof_content: Faker::Quote.famous_last_words)
woof26 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=25', woof_content: Faker::Quote.famous_last_words)
woof27 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=26', woof_content: Faker::Quote.famous_last_words)
woof28 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=27', woof_content: Faker::Quote.famous_last_words)
woof29 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=28', woof_content: Faker::Quote.famous_last_words)
woof30 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=29', woof_content: Faker::Quote.famous_last_words)
woof31 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=30', woof_content: Faker::Quote.famous_last_words)
woof32 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=31', woof_content: Faker::Quote.famous_last_words)
woof33 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=32', woof_content: Faker::Quote.famous_last_words)
woof34 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=33', woof_content: Faker::Quote.famous_last_words)
woof35 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=34', woof_content: Faker::Quote.famous_last_words)
woof36 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=35', woof_content: Faker::Quote.famous_last_words)
woof37 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=36', woof_content: Faker::Quote.famous_last_words)
woof38 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=37', woof_content: Faker::Quote.famous_last_words)
woof39 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=38', woof_content: Faker::Quote.famous_last_words)
woof40 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=39', woof_content: Faker::Quote.famous_last_words)
woof41 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=40', woof_content: Faker::Quote.famous_last_words)
woof42 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=41', woof_content: Faker::Quote.famous_last_words)
woof43 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=42', woof_content: Faker::Quote.famous_last_words)
woof44 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=43', woof_content: Faker::Quote.famous_last_words)
woof45 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=44', woof_content: Faker::Quote.famous_last_words)
woof46 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=45', woof_content: Faker::Quote.famous_last_words)
woof47 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=46', woof_content: Faker::Quote.famous_last_words)
woof48 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=47', woof_content: Faker::Quote.famous_last_words)
woof49 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=48', woof_content: Faker::Quote.famous_last_words)
woof50 = Woof.create!(image_url: 'https://loremflickr.com/320/240/dog?random=49', woof_content: Faker::Quote.famous_last_words)



###
# puts "Adding likes to woofs..."
# like1 = Like.create!(user_id: user4.id, woof_id: woof2.id)
# like2 = Like.create!(user_id: user1.id, woof_id: woof3.id) 
# like3 = Like.create!(user_id: user3.id, woof_id: woof1.id)
# like4 = Like.create!(user_id: user2.id, woof_id: woof3.id)
# like5 = Like.create!(user_id: user4.id, woof_id: woof1.id)
# like6 = Like.create!(user_id: user1.id, woof_id: woof5.id)
# like7 = Like.create!(user_id: user5.id, woof_id: woof4.id)
# end

###
puts "Adding comments to woofs..."
comment1 = Comment.create!(user_id: user2.id, woof_id: woof2.id, comment: Faker::Quote.yoda)
comment2 = Comment.create!(user_id: user1.id, woof_id: woof3.id, comment: Faker::Quote.yoda) 
comment3 = Comment.create!(user_id: user3.id, woof_id: woof1.id, comment: Faker::Quote.yoda) 
comment4 = Comment.create!(user_id: user2.id, woof_id: woof3.id, comment: Faker::Quote.yoda) 
comment5 = Comment.create!(user_id: user4.id, woof_id: woof1.id, comment: Faker::Quote.yoda) 
comment6 = Comment.create!(user_id: user1.id, woof_id: woof5.id, comment: Faker::Quote.yoda) 
comment7 = Comment.create!(user_id: user5.id, woof_id: woof4.id, comment: Faker::Quote.yoda) 
comment8 = Comment.create!(user_id: user8.id, woof_id: woof7.id, comment: Faker::Quote.yoda) 
comment9 = Comment.create!(user_id: user7.id, woof_id: woof8.id, comment: Faker::Quote.yoda)  
comment10 = Comment.create!(user_id: user6.id, woof_id: woof9.id, comment: Faker::Quote.yoda) 
comment11 = Comment.create!(user_id: user12.id, woof_id: woof10.id, comment: Faker::Quote.yoda) 
comment12 = Comment.create!(user_id: user9.id, woof_id: woof11.id, comment: Faker::Quote.yoda) 
comment13 = Comment.create!(user_id: user10.id, woof_id: woof12.id, comment: Faker::Quote.yoda) 
comment14 = Comment.create!(user_id: user11.id, woof_id: woof13.id, comment: Faker::Quote.yoda) 
comment15 = Comment.create!(user_id: user13.id, woof_id: woof14.id, comment: Faker::Quote.yoda) 
comment16 = Comment.create!(user_id: user14.id, woof_id: woof15.id, comment: Faker::Quote.yoda)  
comment17 = Comment.create!(user_id: user15.id, woof_id: woof16.id, comment: Faker::Quote.yoda) 
comment18 = Comment.create!(user_id: user16.id, woof_id: woof17.id, comment: Faker::Quote.yoda) 
comment19 = Comment.create!(user_id: user17.id, woof_id: woof18.id, comment: Faker::Quote.yoda) 
comment20 = Comment.create!(user_id: user18.id, woof_id: woof19.id, comment: Faker::Quote.yoda) 
comment21 = Comment.create!(user_id: user19.id, woof_id: woof20.id, comment: Faker::Quote.yoda) 
comment22 = Comment.create!(user_id: user20.id, woof_id: woof21.id, comment: Faker::Quote.yoda) 
comment23 = Comment.create!(user_id: user21.id, woof_id: woof22.id, comment: Faker::Quote.yoda)  
comment24 = Comment.create!(user_id: user22.id, woof_id: woof23.id, comment: Faker::Quote.yoda) 
comment25 = Comment.create!(user_id: user23.id, woof_id: woof24.id, comment: Faker::Quote.yoda) 
comment26 = Comment.create!(user_id: user24.id, woof_id: woof25.id, comment: Faker::Quote.yoda) 
comment27 = Comment.create!(user_id: user25.id, woof_id: woof26.id, comment: Faker::Quote.yoda) 
comment28 = Comment.create!(user_id: user26.id, woof_id: woof27.id, comment: Faker::Quote.yoda) 
comment29 = Comment.create!(user_id: user27.id, woof_id: woof28.id, comment: Faker::Quote.yoda) 
comment30 = Comment.create!(user_id: user28.id, woof_id: woof29.id, comment: Faker::Quote.yoda)  
comment31 = Comment.create!(user_id: user29.id, woof_id: woof30.id, comment: Faker::Quote.yoda) 
comment32 = Comment.create!(user_id: user30.id, woof_id: woof31.id, comment: Faker::Quote.yoda) 
comment33 = Comment.create!(user_id: user31.id, woof_id: woof32.id, comment: Faker::Quote.yoda) 
comment34 = Comment.create!(user_id: user32.id, woof_id: woof33.id, comment: Faker::Quote.yoda) 
comment35 = Comment.create!(user_id: user33.id, woof_id: woof34.id, comment: Faker::Quote.yoda) 
comment36 = Comment.create!(user_id: user34.id, woof_id: woof35.id, comment: Faker::Quote.yoda) 
comment37 = Comment.create!(user_id: user35.id, woof_id: woof36.id, comment: Faker::Quote.yoda)  
comment38 = Comment.create!(user_id: user36.id, woof_id: woof37.id, comment: Faker::Quote.yoda) 
comment39 = Comment.create!(user_id: user37.id, woof_id: woof38.id, comment: Faker::Quote.yoda) 
comment40 = Comment.create!(user_id: user38.id, woof_id: woof39.id, comment: Faker::Quote.yoda) 
comment41 = Comment.create!(user_id: user39.id, woof_id: woof40.id, comment: Faker::Quote.yoda) 
comment42 = Comment.create!(user_id: user40.id, woof_id: woof41.id, comment: Faker::Quote.yoda) 
comment43 = Comment.create!(user_id: user39.id, woof_id: woof42.id, comment: Faker::Quote.yoda) 
comment44 = Comment.create!(user_id: user38.id, woof_id: woof43.id, comment: Faker::Quote.yoda)  
comment45 = Comment.create!(user_id: user37.id, woof_id: woof44.id, comment: Faker::Quote.yoda) 
comment46 = Comment.create!(user_id: user36.id, woof_id: woof45.id, comment: Faker::Quote.yoda) 
comment47 = Comment.create!(user_id: user35.id, woof_id: woof46.id, comment: Faker::Quote.yoda) 
comment48 = Comment.create!(user_id: user34.id, woof_id: woof47.id, comment: Faker::Quote.yoda) 
comment49 = Comment.create!(user_id: user33.id, woof_id: woof48.id, comment: Faker::Quote.yoda) 
comment50 = Comment.create!(user_id: user32.id, woof_id: woof49.id, comment: Faker::Quote.yoda) 
comment51 = Comment.create!(user_id: user31.id, woof_id: woof50.id, comment: Faker::Quote.yoda)  
comment52 = Comment.create!(user_id: user30.id, woof_id: woof49.id, comment: Faker::Quote.yoda) 
comment53 = Comment.create!(user_id: user29.id, woof_id: woof48.id, comment: Faker::Quote.yoda) 
comment54 = Comment.create!(user_id: user28.id, woof_id: woof47.id, comment: Faker::Quote.yoda) 
comment55 = Comment.create!(user_id: user27.id, woof_id: woof46.id, comment: Faker::Quote.yoda) 
comment56 = Comment.create!(user_id: user26.id, woof_id: woof45.id, comment: Faker::Quote.yoda) 
puts "Done seeding!"